### ISSUE TITLE
A few loose ends

### ISSUE THREAD

**Issue by giganteous** [cloudflare/promsaint#2]
Hi @Kellel ,

Could you help me with a few points?

I don't know yet how I should group the alerts from nagios? Are you grouping by notify? Or do you use something smarter?

And what generic inhibition rules would be smart? This is what I would do:
```yaml
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']
```

Do you repeat yourself in the alertmanager configuration wrt the receivers of alerts versus the notify argument passed from nagios? That seems double work, is that the case?

Tia
